#!/usr/bin/env ruby

require 'optparse'
require 'sqlite3'
require_relative 'models/recipe.rb'
require_relative 'models/user_interface.rb'
require_relative 'models/log.rb'

interface = UserInterface.new
interface.parse_options
interface.check_for_missing_name
interface.check_for_missing_options
interface.execute_command_line_command

Log.test_output_theoretically_did(interface)