#!/usr/bin/env ruby

require 'optparse'
require 'sqlite3'
require_relative 'models/recipe.rb'
require_relative 'models/user_interface.rb'

interface = UserInterface.new
interface.parse_options
interface.check_for_missing_name
interface.check_for_missing_options

case interface.command
when "create"
  Recipe.create(interface.name, interface.options)
end

puts "Theoretically did: #{interface.command} recipe #{interface.name}; with ingredients #{interface.options[:ingredients]}; with directions #{interface.options[:directions]}; time #{interface.options[:time]}; meal #{interface.options[:meal]}; serves #{interface.options[:serves]}; calories #{interface.options[:calories]}." if interface.options[:test_output]